Jlou/test argocd vault deployment
Cosmo-Tech/terraform-azure-cosmotech-common pull request #54
Opened 2024-08-12 10:22 UTC by JoelLourenco

Add 3 new modules and variables for testing

2024-08-16 15:45 UTC, MohcineTor reviewed
C'est bon pour moi, je vois juste cette petite remarque :+1:

2024-08-17 11:06 UTC, JoelLourenco commented on create_vault/main.tf
> +
Done

2024-08-17 11:06 UTC, JoelLourenco commented on create_argocd/main.tf
> +
Done

2024-08-17 11:07 UTC, JoelLourenco commented on create-vault-secrets-operator/main.tf
> +}
Done

2024-08-19 11:54 UTC, vysahjk commented
tu peux refaire une check avec validate please ?

2024-08-19 12:00 UTC, vysahjk commented on create_argocd/argocd-setup.sh
> +NAMESPACE=$1
check des variables ?

2024-08-19 12:00 UTC, vysahjk commented on create_argocd/get-password.sh
> +namespace=$1
check des variables ?

2024-08-19 12:01 UTC, vysahjk requested changes

2024-08-19 12:01 UTC, vysahjk commented on create_vault/unseal.sh
> +NAMESPACE=$1
check variables ?

2024-08-19 15:22 UTC, closed without merging